export const LAY_DANH_SACH_SAN_PHAM = "LAY_DANH_SACH_SAN_PHAM";
export const LAY_DANH_SACH_SAN_PHAM_SUCCESS = "LAY_DANH_SACH_SAN_PHAM_SUCCESS";
export const LAY_DANH_SACH_SAN_PHAM_FAILED = "LAY_DANH_SACH_SAN_PHAM_FAILED";

export const ADD_MY_CART = "ADD_MY_CART";
export const ADD_MY_CART_SUCCESS = "ADD_MY_CART_SUCCESS";
export const RESET_CART = "RESET_CART";

export const CHECK_OUT = "CHECK_OUT";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";

export const GET_ORDER_LIST = "GET_ORDER_LIST";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
